FROM nvidia/cuda:11.7.0-cudnn8-devel-ubuntu20.04

ARG GIT_URL=https://github.com/mlcommons/algorithmic-efficiency.git

# Installing machine packages
RUN echo "Setting up machine"
RUN apt-get update
RUN apt-get install -y curl tar
RUN apt-get install -y git python3 pip wget

# Install GCP tools
RUN echo "Setting up gsutil"
RUN curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-413.0.0-linux-x86_64.tar.gz
RUN tar -xf google-cloud-cli-413.0.0-linux-x86_64.tar.gz
RUN yes | ./google-cloud-sdk/install.sh

# Directory setup for input and output
RUN echo "Todo: mount directories Setting up directories"
RUN mkdir -p data/
RUN mkdir -p experiment_runs/

# Install Algorithmic efficiency repo
RUN echo "Setting up algorithmic_efficiency repo"
# TEMP disable this for dev
# RUN git clone $GIT_URL 
COPY ../ /algorithmic-efficiency
RUN cd algorithmic-efficiency && pip install -e '.[full]'

RUN cd algorithmic-efficiency && pip install -e '.[jax_gpu]' -f 'https://storage.googleapis.com/jax-releases/jax_cuda_releases.html'
RUN cd algorithmic-efficiency && pip install -e '.[pytorch_gpu]' -f 'https://download.pytorch.org/whl/torch_stable.html'

RUN cd algorithmic-efficiency && git pull 
# RUN chmod a+x algorithmic-efficiency/docker/scripts/startup_dev.sh

# ENTRYPOINT ["sh", "-c", "algorithmic-efficiency/docker/scripts/startup_dev.sh"]
